language: ruby
rvm:
  - 2.4.1
  - 2.3.9
  - 2.2.7
  - 2.1.10
  - 2.0.0
  - jruby-1.7.19
branches:
  only:
    - master
bundler_args: --without development
script: bundle exec rspec -fdoc
gemfile: Gemfile.travis
dist: trusty
