language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0
  - jruby-1.7.19
branches:
  only:
    - master
bundler_args: --without development
script: bundle exec rspec -fdoc
gemfile: Gemfile.travis
